
on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Java 11 build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: true
      - run: |
          mkdir out
          javac -d out pickle/*.java


  test:
    name: Pickle Unit tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2

      - run: |
          mkdir out
          javac -d out pickle/*.java
          javac -d out -cp out:junit-platform-console-standalone-1.3.1.jar pickle/tests/DateTest.java
          java -jar junit-platform-console-standalone-1.3.1.jar --class-path out --scan-class-path
